### user API
### Registration
POST http://localhost:8000/api/v1/users
Content-type: application/json

{
    "name": "test name",
    "email": "test@email",
    "password": "123456"
}

### User Login
POST http://localhost:8000/api/v1/users/login
Content-type: application/json

{
    "name": "test name",
    "email": "test@email",
    "password": "123456"
}
